FROM node:20-alpine AS builder
WORKDIR /app

COPY apps/web/package.json ./package.json
RUN npm install

COPY apps/web ./
ARG NEXT_PUBLIC_API_URL=http://api.techfieldgps.vemontech.com
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/node_modules ./node_modules

EXPOSE 3001
CMD ["npm", "run", "start"]
